"""Removed disk_filepath field for file

Revision ID: 3b8b51beb911
Revises: 79368920e70e
Create Date: 2024-11-07 19:06:48.902841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b8b51beb911'
down_revision: Union[str, None] = '79368920e70e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_column('disk_filepath')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disk_filepath', sa.VARCHAR(), nullable=False))

    # ### end Alembic commands ###
