"""Potential fix to FolderEntity

Revision ID: 492f82801e43
Revises: 3cfde12aa1f8
Create Date: 2024-10-29 12:48:20.198651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "492f82801e43"
down_revision: Union[str, None] = "3cfde12aa1f8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
