"""Add is_public column to files and folder

Revision ID: a5b4e65c5e88
Revises: 3b8b51beb911
Create Date: 2024-11-21 20:55:52.484690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5b4e65c5e88'
down_revision: Union[str, None] = '3b8b51beb911'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=False))

    with op.batch_alter_table('folders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('folders', schema=None) as batch_op:
        batch_op.drop_column('is_public')

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_column('is_public')

    # ### end Alembic commands ###
